/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.lista;

import java.util.Scanner;

/**
 *
 * @author Aluno
 */
public class CalculadoraPizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizzada
     */
    public CalculadoraPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto01 = new javax.swing.JLabel();
        lblTexto02 = new javax.swing.JLabel();
        lblTexto03 = new javax.swing.JLabel();
        lblTexto04 = new javax.swing.JLabel();
        btnCalcular01 = new javax.swing.JButton();
        tfCampo1 = new javax.swing.JTextField();
        tfCampo2 = new javax.swing.JTextField();
        tfCampo3 = new javax.swing.JTextField();
        tfCampo4 = new javax.swing.JTextField();
        lblTexto05 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTexto01.setForeground(new java.awt.Color(0, 51, 255));
        lblTexto01.setText("Valor de uma pizza:");

        lblTexto02.setForeground(new java.awt.Color(0, 51, 255));
        lblTexto02.setText("Sabor da pizza");

        lblTexto03.setForeground(new java.awt.Color(0, 51, 255));
        lblTexto03.setText("Quantidade de pessoas que irá rachar a conta:");

        lblTexto04.setForeground(new java.awt.Color(0, 51, 255));
        lblTexto04.setText("valor máximo que as pessoas aceitam rachar:");

        btnCalcular01.setBackground(new java.awt.Color(51, 51, 51));
        btnCalcular01.setForeground(new java.awt.Color(51, 204, 0));
        btnCalcular01.setText("Calcular Pizza");
        btnCalcular01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular01ActionPerformed(evt);
            }
        });

        lblTexto05.setText("Pizza vai rolar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnCalcular01))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTexto05, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTexto01)
                                    .addComponent(lblTexto02)
                                    .addComponent(lblTexto03)
                                    .addComponent(lblTexto04))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(tfCampo2)
                                    .addComponent(tfCampo3)
                                    .addComponent(tfCampo4))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto02)
                    .addComponent(tfCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto03)
                    .addComponent(tfCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto04)
                    .addComponent(tfCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto05, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcular01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular01ActionPerformed
        // TODO add your handling code here:
        Double valorPizza = Double.valueOf(tfCampo1.getText());
        String saborPizza = String.valueOf(tfCampo2.getText());
        Integer pessoasParaRachar = Integer.valueOf(tfCampo3.getText());
        Double valorMax = Double.valueOf(tfCampo4.getText());
        Double valorPorPessoaPizza = valorPizza/pessoasParaRachar;
        Double deveriaCustar = pessoasParaRachar*valorMax;
        String msg = "";
        
        
        if(valorPorPessoaPizza <= valorMax){
            msg = (String.format("A pizza de %s será dividida entre %d"
                +"pessoas. R$ %.2f para cada", saborPizza, pessoasParaRachar,valorPorPessoaPizza));
        } else {
            msg = (String.format("Deu ruim no racha. A pizza "
                    + "deveria custar no máximo R$%.2f" ,deveriaCustar));
        }
        
        lblTexto05.setText(msg);
    }//GEN-LAST:event_btnCalcular01ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular01;
    private javax.swing.JLabel lblTexto01;
    private javax.swing.JLabel lblTexto02;
    private javax.swing.JLabel lblTexto03;
    private javax.swing.JLabel lblTexto04;
    private javax.swing.JLabel lblTexto05;
    private javax.swing.JTextField tfCampo1;
    private javax.swing.JTextField tfCampo2;
    private javax.swing.JTextField tfCampo3;
    private javax.swing.JTextField tfCampo4;
    // End of variables declaration//GEN-END:variables
}
