/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.lista;

/**
 *
 * @author Aluno
 */
public class Sorveteria extends javax.swing.JFrame {

    /**
     * Creates new form Sorveteria
     */
    public Sorveteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCasquinha = new javax.swing.JButton();
        btnSundae = new javax.swing.JButton();
        btnMilkshake = new javax.swing.JButton();
        CaixaDeTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Qual sorvete deseja?");

        btnCasquinha.setText("Casquinha");
        btnCasquinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasquinhaActionPerformed(evt);
            }
        });

        btnSundae.setText("Sundae");
        btnSundae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSundaeActionPerformed(evt);
            }
        });

        btnMilkshake.setText("Milkshake");
        btnMilkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilkshakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaixaDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCasquinha)
                                .addGap(18, 18, 18)
                                .addComponent(btnSundae, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnMilkshake))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCasquinha)
                    .addComponent(btnSundae)
                    .addComponent(btnMilkshake))
                .addGap(30, 30, 30)
                .addComponent(CaixaDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSundaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSundaeActionPerformed
        //sundae custa R$ 5,00
        String valorSundae = "sundae custa R$ 5,00";
        CaixaDeTexto.setText(valorSundae);
        
    }//GEN-LAST:event_btnSundaeActionPerformed

    private void btnCasquinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasquinhaActionPerformed
        //casquinha custa R$ 2,00
        String valorCasquinha = "casquinha custa R$ 2,00";
        CaixaDeTexto.setText(valorCasquinha);
    }//GEN-LAST:event_btnCasquinhaActionPerformed

    private void btnMilkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilkshakeActionPerformed
        //milkshake custa R$ 7,00
        String valorMilkshake = "milkshake custa R$ 7,00";
        CaixaDeTexto.setText(valorMilkshake);
    }//GEN-LAST:event_btnMilkshakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sorveteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sorveteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sorveteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sorveteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sorveteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaixaDeTexto;
    private javax.swing.JButton btnCasquinha;
    private javax.swing.JButton btnMilkshake;
    private javax.swing.JButton btnSundae;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
