/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto3.poo1;

import java.awt.Color;

/**
 *
 * @author diego
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        tfCampo1 = new javax.swing.JTextField();
        tfCampo2 = new javax.swing.JTextField();
        tfCampo3 = new javax.swing.JTextField();
        btnAcao1 = new javax.swing.JButton();
        btnAcao2 = new javax.swing.JButton();
        btnAcao3 = new javax.swing.JButton();
        btnAcao5 = new javax.swing.JButton();
        btnAcao4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTexto1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(28, 0, 255));
        lblTexto1.setText("1º label");

        lblTexto2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(255, 0, 0));
        lblTexto2.setText("segundo label");

        lblTexto3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(1, 151, 19));
        lblTexto3.setText("Terceirona");

        btnAcao1.setText("Açao 01");
        btnAcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao1ActionPerformed(evt);
            }
        });

        btnAcao2.setText("Açao 02");
        btnAcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao2ActionPerformed(evt);
            }
        });

        btnAcao3.setText("Açao 03");
        btnAcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao3ActionPerformed(evt);
            }
        });

        btnAcao5.setText("Açao 05");
        btnAcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao5ActionPerformed(evt);
            }
        });

        btnAcao4.setText("Açao 04");
        btnAcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTexto1)
                    .addComponent(tfCampo1)
                    .addComponent(btnAcao1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTexto2)
                    .addComponent(tfCampo2)
                    .addComponent(btnAcao2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTexto3)
                    .addComponent(tfCampo3)
                    .addComponent(btnAcao3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnAcao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnAcao5)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto1)
                    .addComponent(lblTexto2)
                    .addComponent(lblTexto3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao1)
                    .addComponent(btnAcao2)
                    .addComponent(btnAcao3))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao5)
                    .addComponent(btnAcao4))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao1ActionPerformed

        // Existe um padrao utilizado no meio da programaçao chamado
        // GET e SET
        // Get serve para recuperar algo ou algum valor.
        // Set serve para alterar alguma caracteristica.
        lblTexto1.setText("Alguem clicou!");
    }//GEN-LAST:event_btnAcao1ActionPerformed

    private void btnAcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao2ActionPerformed

//Resoluçao 01:
//        criando variavel que armazenara o conteudo do input
//        String texto = tfCampo2.getText();
//        lblTexto2.setText(texto);
//Resoluçao 02:
        lblTexto2.setText(tfCampo2.getText());
    }//GEN-LAST:event_btnAcao2ActionPerformed

    private void btnAcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao3ActionPerformed

        // Exemplo de troca de cores dos objetos
        
        // Valores em hexa
        lblTexto3.setForeground(Color.decode("#e67e22"));
        
        // Cores predefinidas
        lblTexto3.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_btnAcao3ActionPerformed

    private void btnAcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao4ActionPerformed
        
        //Desafio 01 -> Açao 04
        
        String textoDigitado = tfCampo1.getText();
        
        lblTexto1.setText(textoDigitado);
        lblTexto2.setText(textoDigitado);
        lblTexto3.setText(textoDigitado);
        
    }//GEN-LAST:event_btnAcao4ActionPerformed

    private void btnAcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao5ActionPerformed
        
        // Desafio 02 -> Açao 05
        
        lblTexto2.setForeground(lblTexto1.getForeground());
        lblTexto3.setForeground(lblTexto1.getForeground());
        
    }//GEN-LAST:event_btnAcao5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao1;
    private javax.swing.JButton btnAcao2;
    private javax.swing.JButton btnAcao3;
    private javax.swing.JButton btnAcao4;
    private javax.swing.JButton btnAcao5;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JTextField tfCampo1;
    private javax.swing.JTextField tfCampo2;
    private javax.swing.JTextField tfCampo3;
    // End of variables declaration//GEN-END:variables
}
